# Generated by Django 5.0.3 on 2024-04-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresponse',
            old_name='form_id',
            new_name='form',
        ),
    ]
