# Generated by Django 5.0.3 on 2024-04-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answering', '0002_rename_form_id_formresponse_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormResponse',
        ),
    ]
