# Generated by Django 5.0.3 on 2024-03-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_size', models.CharField(max_length=2)),
                ('point', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('lower_bound', models.IntegerField(max_length=3)),
                ('upper_bound', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=450)),
                ('design', models.JSONField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('publish_timestamp', models.DateTimeField(null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_management.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_point', to='form_management.point')),
            ],
        ),
    ]
