# Generated by Django 5.0.3 on 2024-03-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lower_bound',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='upper_bound',
            field=models.IntegerField(),
        ),
    ]
