# Generated by Django 5.0.3 on 2024-03-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0002_alter_point_lower_bound_alter_point_upper_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_management.category'),
        ),
    ]
