# Generated by Django 5.0.3 on 2024-03-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0004_alter_point_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
