# Generated by Django 5.0.3 on 2024-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_management", "0006_formresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="form_pic",
            field=models.ImageField(
                default="static/answering/imgs/no-pic.png",
                null=True,
                upload_to="static/answering/imgs",
            ),
        ),
    ]
