# Generated by Django 5.0.3 on 2024-04-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0007_form_form_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='context',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_pic',
            field=models.ImageField(default='static/form_management/imgs/no-pic.png', null=True, upload_to='static/form_management/imgs'),
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
