# Generated by Django 5.0.3 on 2024-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0008_point_context_alter_form_form_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='context',
            field=models.CharField(blank=True, choices=[('SEL', 'Selling'), ('ANS', 'Answering')], max_length=3, null=True),
        ),
    ]
