# Generated by Django 5.0.3 on 2024-04-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0009_alter_point_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_selling_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_selling_point', to='form_management.point'),
        ),
    ]
